// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: registry/registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider string                      `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Local    *RegistryOption_LocalOption `protobuf:"bytes,2,opt,name=local,proto3" json:"local,omitempty"`
	Etcd     *RegistryOption_EtcdOption  `protobuf:"bytes,3,opt,name=etcd,proto3" json:"etcd,omitempty"`
}

func (x *RegistryOption) Reset() {
	*x = RegistryOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistryOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryOption) ProtoMessage() {}

func (x *RegistryOption) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryOption.ProtoReflect.Descriptor instead.
func (*RegistryOption) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryOption) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegistryOption) GetLocal() *RegistryOption_LocalOption {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *RegistryOption) GetEtcd() *RegistryOption_EtcdOption {
	if x != nil {
		return x.Etcd
	}
	return nil
}

type RegistryOption_LocalOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*RegistryOption_LocalOption_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *RegistryOption_LocalOption) Reset() {
	*x = RegistryOption_LocalOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistryOption_LocalOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryOption_LocalOption) ProtoMessage() {}

func (x *RegistryOption_LocalOption) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryOption_LocalOption.ProtoReflect.Descriptor instead.
func (*RegistryOption_LocalOption) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RegistryOption_LocalOption) GetEntries() []*RegistryOption_LocalOption_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RegistryOption_EtcdOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password  string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Endpoints []string `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *RegistryOption_EtcdOption) Reset() {
	*x = RegistryOption_EtcdOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistryOption_EtcdOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryOption_EtcdOption) ProtoMessage() {}

func (x *RegistryOption_EtcdOption) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryOption_EtcdOption.ProtoReflect.Descriptor instead.
func (*RegistryOption_EtcdOption) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RegistryOption_EtcdOption) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryOption_EtcdOption) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistryOption_EtcdOption) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type RegistryOption_LocalOption_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version   string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Endpoints []string `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *RegistryOption_LocalOption_Entry) Reset() {
	*x = RegistryOption_LocalOption_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistryOption_LocalOption_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryOption_LocalOption_Entry) ProtoMessage() {}

func (x *RegistryOption_LocalOption_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryOption_LocalOption_Entry.ProtoReflect.Descriptor instead.
func (*RegistryOption_LocalOption_Entry) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *RegistryOption_LocalOption_Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegistryOption_LocalOption_Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryOption_LocalOption_Entry) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegistryOption_LocalOption_Entry) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_registry_registry_proto protoreflect.FileDescriptor

var file_registry_registry_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x7a, 0x65, 0x72, 0x6f, 0x2e,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x22, 0xcf, 0x03, 0x0a, 0x0e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x2e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x05, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x3c, 0x0a, 0x04, 0x65, 0x74, 0x63, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x2e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x74, 0x63, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x04, 0x65, 0x74, 0x63, 0x64, 0x1a, 0xbd, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x7a, 0x65, 0x72, 0x6f, 0x2e, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x1a, 0x63, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x62, 0x0a, 0x0a, 0x45, 0x74, 0x63, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x25, 0x5a, 0x20, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x63, 0x6f, 0x73, 0x69, 0x70,
	0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0xf8, 0x01,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_registry_registry_proto_rawDescOnce sync.Once
	file_registry_registry_proto_rawDescData = file_registry_registry_proto_rawDesc
)

func file_registry_registry_proto_rawDescGZIP() []byte {
	file_registry_registry_proto_rawDescOnce.Do(func() {
		file_registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_registry_registry_proto_rawDescData)
	})
	return file_registry_registry_proto_rawDescData
}

var file_registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_registry_registry_proto_goTypes = []interface{}{
	(*RegistryOption)(nil),                   // 0: zero.registry.RegistryOption
	(*RegistryOption_LocalOption)(nil),       // 1: zero.registry.RegistryOption.LocalOption
	(*RegistryOption_EtcdOption)(nil),        // 2: zero.registry.RegistryOption.EtcdOption
	(*RegistryOption_LocalOption_Entry)(nil), // 3: zero.registry.RegistryOption.LocalOption.Entry
}
var file_registry_registry_proto_depIdxs = []int32{
	1, // 0: zero.registry.RegistryOption.local:type_name -> zero.registry.RegistryOption.LocalOption
	2, // 1: zero.registry.RegistryOption.etcd:type_name -> zero.registry.RegistryOption.EtcdOption
	3, // 2: zero.registry.RegistryOption.LocalOption.entries:type_name -> zero.registry.RegistryOption.LocalOption.Entry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_registry_registry_proto_init() }
func file_registry_registry_proto_init() {
	if File_registry_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_registry_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistryOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registry_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistryOption_LocalOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registry_registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistryOption_EtcdOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registry_registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistryOption_LocalOption_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_registry_registry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registry_registry_proto_goTypes,
		DependencyIndexes: file_registry_registry_proto_depIdxs,
		MessageInfos:      file_registry_registry_proto_msgTypes,
	}.Build()
	File_registry_registry_proto = out.File
	file_registry_registry_proto_rawDesc = nil
	file_registry_registry_proto_goTypes = nil
	file_registry_registry_proto_depIdxs = nil
}
