// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: middleware/cors/cors.proto

package cors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CorsConfig defines the CORS configuration
type CorsConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed_origins specifies the allowed origins for CORS requests
	// Use "*" to allow all origins
	AllowedOrigins []string `protobuf:"bytes,1,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	// allowed_methods specifies the allowed HTTP methods for CORS requests
	// Common values: GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH
	AllowedMethods []string `protobuf:"bytes,2,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`
	// allowed_headers specifies the allowed headers for CORS requests
	AllowedHeaders []string `protobuf:"bytes,3,rep,name=allowed_headers,json=allowedHeaders,proto3" json:"allowed_headers,omitempty"`
	// exposed_headers specifies the headers that are exposed to the client
	ExposedHeaders []string `protobuf:"bytes,4,rep,name=exposed_headers,json=exposedHeaders,proto3" json:"exposed_headers,omitempty"`
	// allow_credentials indicates whether credentials are allowed
	AllowCredentials bool `protobuf:"varint,5,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	// max_age specifies the maximum age for preflight requests cache (in seconds)
	MaxAge        int32 `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorsConfig) Reset() {
	*x = CorsConfig{}
	mi := &file_middleware_cors_cors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorsConfig) ProtoMessage() {}

func (x *CorsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_middleware_cors_cors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorsConfig.ProtoReflect.Descriptor instead.
func (*CorsConfig) Descriptor() ([]byte, []int) {
	return file_middleware_cors_cors_proto_rawDescGZIP(), []int{0}
}

func (x *CorsConfig) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

func (x *CorsConfig) GetAllowedMethods() []string {
	if x != nil {
		return x.AllowedMethods
	}
	return nil
}

func (x *CorsConfig) GetAllowedHeaders() []string {
	if x != nil {
		return x.AllowedHeaders
	}
	return nil
}

func (x *CorsConfig) GetExposedHeaders() []string {
	if x != nil {
		return x.ExposedHeaders
	}
	return nil
}

func (x *CorsConfig) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *CorsConfig) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

var File_middleware_cors_cors_proto protoreflect.FileDescriptor

const file_middleware_cors_cors_proto_rawDesc = "" +
	"\n" +
	"\x1amiddleware/cors/cors.proto\x12\x16kratos.middleware.cors\"\xf6\x01\n" +
	"\n" +
	"CorsConfig\x12'\n" +
	"\x0fallowed_origins\x18\x01 \x03(\tR\x0eallowedOrigins\x12'\n" +
	"\x0fallowed_methods\x18\x02 \x03(\tR\x0eallowedMethods\x12'\n" +
	"\x0fallowed_headers\x18\x03 \x03(\tR\x0eallowedHeaders\x12'\n" +
	"\x0fexposed_headers\x18\x04 \x03(\tR\x0eexposedHeaders\x12+\n" +
	"\x11allow_credentials\x18\x05 \x01(\bR\x10allowCredentials\x12\x17\n" +
	"\amax_age\x18\x06 \x01(\x05R\x06maxAgeB.Z,github.com/cocosip/zero/middleware/cors;corsb\x06proto3"

var (
	file_middleware_cors_cors_proto_rawDescOnce sync.Once
	file_middleware_cors_cors_proto_rawDescData []byte
)

func file_middleware_cors_cors_proto_rawDescGZIP() []byte {
	file_middleware_cors_cors_proto_rawDescOnce.Do(func() {
		file_middleware_cors_cors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_middleware_cors_cors_proto_rawDesc), len(file_middleware_cors_cors_proto_rawDesc)))
	})
	return file_middleware_cors_cors_proto_rawDescData
}

var file_middleware_cors_cors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_middleware_cors_cors_proto_goTypes = []any{
	(*CorsConfig)(nil), // 0: kratos.middleware.cors.CorsConfig
}
var file_middleware_cors_cors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_middleware_cors_cors_proto_init() }
func file_middleware_cors_cors_proto_init() {
	if File_middleware_cors_cors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_middleware_cors_cors_proto_rawDesc), len(file_middleware_cors_cors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_middleware_cors_cors_proto_goTypes,
		DependencyIndexes: file_middleware_cors_cors_proto_depIdxs,
		MessageInfos:      file_middleware_cors_cors_proto_msgTypes,
	}.Build()
	File_middleware_cors_cors_proto = out.File
	file_middleware_cors_cors_proto_goTypes = nil
	file_middleware_cors_cors_proto_depIdxs = nil
}
