// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: cors/cors.proto

package cors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CorsOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origins          []string `protobuf:"bytes,1,rep,name=origins,proto3" json:"origins,omitempty"`
	Methods          []string `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	Headers          []string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	AllowCredentials bool     `protobuf:"varint,4,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
}

func (x *CorsOption) Reset() {
	*x = CorsOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cors_cors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorsOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorsOption) ProtoMessage() {}

func (x *CorsOption) ProtoReflect() protoreflect.Message {
	mi := &file_cors_cors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorsOption.ProtoReflect.Descriptor instead.
func (*CorsOption) Descriptor() ([]byte, []int) {
	return file_cors_cors_proto_rawDescGZIP(), []int{0}
}

func (x *CorsOption) GetOrigins() []string {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *CorsOption) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *CorsOption) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CorsOption) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

var File_cors_cors_proto protoreflect.FileDescriptor

var file_cors_cors_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x7a, 0x65, 0x72, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x73, 0x22, 0x87, 0x01, 0x0a,
	0x0a, 0x43, 0x6f, 0x72, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x42, 0x0e, 0x5a, 0x09, 0x7a, 0x65, 0x72, 0x6f, 0x2f, 0x63,
	0x6f, 0x72, 0x73, 0xf8, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cors_cors_proto_rawDescOnce sync.Once
	file_cors_cors_proto_rawDescData = file_cors_cors_proto_rawDesc
)

func file_cors_cors_proto_rawDescGZIP() []byte {
	file_cors_cors_proto_rawDescOnce.Do(func() {
		file_cors_cors_proto_rawDescData = protoimpl.X.CompressGZIP(file_cors_cors_proto_rawDescData)
	})
	return file_cors_cors_proto_rawDescData
}

var file_cors_cors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cors_cors_proto_goTypes = []interface{}{
	(*CorsOption)(nil), // 0: zero.cors.CorsOption
}
var file_cors_cors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cors_cors_proto_init() }
func file_cors_cors_proto_init() {
	if File_cors_cors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cors_cors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorsOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cors_cors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cors_cors_proto_goTypes,
		DependencyIndexes: file_cors_cors_proto_depIdxs,
		MessageInfos:      file_cors_cors_proto_msgTypes,
	}.Build()
	File_cors_cors_proto = out.File
	file_cors_cors_proto_rawDesc = nil
	file_cors_cors_proto_goTypes = nil
	file_cors_cors_proto_depIdxs = nil
}
